title: Test Blog
description: >- # this means to ignore newlines until "baseurl:"
  My blogging site, for me to write epic blogs on programming and programming related things
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  StrG30

# Build settings
theme: minima
plugins:
  - jekyll-feed

minima:
  skin: dark
